// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RazorPagesMusic.Migrations
{
    [DbContext(typeof(RazorPagesMusicContext))]
    [Migration("20220302041639_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("RazorPagesMusic.Models.Music", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MusicGenre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MusicReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameofArtists")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Review")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Music");
                });
#pragma warning restore 612, 618
        }
    }
}
